#!/bin/bash
# Dotfiles install script

# Use this script to install the dotfiles either locally (default) or remotely to the given user and host.

# Synopsis
# install [-R [user@]host]

install_mode='local'

while getopts "R:" Option
do
  case $Option in
    R ) install_mode='remote'; remote_host=$OPTARG;;   # Specify remote user and host
    * ) echo "Usage: `basename $0` [-R [user@]host]";; # DEFAULT
  esac
done

# Pre-install tests
function do_preflight () {
  echo 'Doing preflight tests...'
  manifest=(~/.bashrc ~/.bash_profile ~/bin/vcprompt)
  for file in ${manifest[@]}
  do
    if [[ -e $file ]]; then
      echo "${file} exists"
      preflight_failed=1
    fi
  done
  
  if [[ $preflight_failed ]]; then
    echo "Install aborted!" # TODO: Use -f to force overwrite
    return 1
  else
    return 0
  fi
}

# Local install
function do_local_install () {
  if [[ ! -d ~/bin ]]; then
    echo "Creating ~/bin directory"
    mkdir ~/bin
    if [[ $? -gt 0 ]]; then
      exit_with_error 'Error creating ~/bin directory'
    fi
  fi
  echo 'Copying vcprompt binary to ~/bin'
  cp bin/vcprompt ~/bin/vcprompt
  if [[ $? -gt 0 ]]; then
    exit_with_error 'Error copying vcprompt binary'
  fi
  echo 'Symlinking .bash_profile'
  ln -s ~/.dotfiles/bash_profile ~/.bash_profile
  if [[ $? -gt 0 ]]; then
    exit_with_error 'Error symlinking .bash_profile'
  fi
  echo 'Symlinking .bashrc'
  ln -s ~/.dotfiles/bashrc ~/.bashrc
  if [[ $? -gt 0 ]]; then
    exit_with_error 'Error symlinking .bashrc'
  fi
  echo 'Dotfiles installed successfully!'
}

# TODO: Remote install script

function exit_with_error () {
  echo $1
  echo 'Install failed!'
  exit 1
}

# - - - - - - - - - - -

case $install_mode in
  'local' )
    do_preflight
    if [[ $? -eq 0 ]]; then
      do_local_install
    fi
  ;;
  'remote' )
    echo 'Not implemented yet'
  ;;
esac

exit 0
